### ISSUE TITLE
当 Separator 设置为 ## 时，三级标题也会识别为标签页

### ISSUE THREAD

**Issue by jianwu003** [xhuajin/obsidian-tabs#1]
代码块如下

```tabs
##  What is Markdown?
It’s a plain text format for writing structured documents, based on formatting conventions froma email and usenet.

...

# Heading 1

##  Heading 2
...ceshi

### Heading3
这个不显示为标签页
```
之前我也稍微改了一下这个插件，就是把标签页标题用 md 语法识别，希望作者能稍微修改一下，下面时源码还有编译好的插件
![image](https://github.com/xhuajin/obsidian-tabs/assets/159551078/2f927a7e-2e80-496a-8726-8c57b1ef183d)
![image](https://github.com/xhuajin/obsidian-tabs/assets/159551078/9f91f539-4e54-40e5-98f1-4f81a48a11ed)
![image](https://github.com/xhuajin/obsidian-tabs/assets/159551078/09889024-2d3c-400d-9cf8-92a7d0466631)

[src.zip](https://github.com/xhuajin/obsidian-tabs/files/15455158/src.zip)
[008@CodeTab.zip](https://github.com/xhuajin/obsidian-tabs/files/15455187/008%40CodeTab.zip)

**Comment by xhuajin** [comment]
抱歉才看到这个issue。这确实是个问题，插件写的有点久了，我抽空捋一下插件识别 separator 的逻辑改进一下。

**Comment by jianwu003** [comment]
好的，麻烦开发者了

**Comment by xhuajin** [comment]
已经优化了解析逻辑，见v1.1.0

**Comment by jianwu003** [comment]
好的，感谢作者
