### ISSUE TITLE
[FR] 渲染空的tabs代码块

### ISSUE THREAD

**Issue by XMB-7** [xhuajin/obsidian-tabs#10]
目前对于
``````
```tabs
```
``````
是渲染为空的, 希望将之与
``````
```tabs
tab:
```
``````
等效, 亦即能把tab栏渲染出来, 从而方便用户只需要键入前者, 即可通过粘贴来快速创建新的tab.

![image](https://github.com/xhuajin/obsidian-tabs/assets/65625632/5ce987fa-a8cf-4dd0-a1b6-f8b75a2d9d0f)

**Comment by xhuajin** [comment]
1.1.0 可以渲染空 Tabs 组件
