### ISSUE TITLE
与第三方主题minimal不兼容

### ISSUE THREAD

**Issue by XMB-7** [xhuajin/obsidian-tabs#12]
使用默认主题没有任何问题.
开启minimal主题, 
鼠标悬浮于tabs上丢失高亮边框;
当双击tabs编辑时, 存在如下图的显示问题, 背景里出现了代码块里的内容'tab: a'以及aaa, 此时也能进行修改, 只不过是视觉效果不好, 当点击保存退出内容编辑时, 画面恢复正常. 

![image](https://github.com/xhuajin/obsidian-tabs/assets/65625632/02deec61-70dd-4bdd-97df-997abeac5716)

**Comment by xhuajin** [comment]
fix

**Comment by XMB-7** [comment]
感谢修复, 使用minimal仍然没有显示代码块边框高亮, 请问是还需要自行调整某些css设置吗
![recording](https://github.com/xhuajin/obsidian-tabs/assets/65625632/2a525388-45e1-4fa6-99ca-ddf6c1559214)

**Comment by xhuajin** [comment]
边框由主题和css决定，插件没有特地增加和隐藏边框，可以增加css添加边框

.markdown-source-view.mod-cm6 .cm-embed-block:not(.cm-table-widget) {
    box-shadow: none !important;
    border: 3px solid transparent;
    transition: 200ms var(--anim-motion-smooth);
    border-radius: var(--radius-l) !important;
}
