### ISSUE TITLE
[FR] 双击修改哪一标签页的内容, 保存之后, 能自动切换回显示哪一标签页.

### ISSUE THREAD

**Issue by XMB-7** [xhuajin/obsidian-tabs#13]
比如在tab5上双击, 修改其中内容并保存编辑, 此时只会自动切换显示tab1, 所以还需要手动切换回tab5. 
如果可以在保存修改后仍能显示tab5就再好不过了.

**Comment by xhuajin** [comment]
试试 v1.1.0
