### ISSUE TITLE
Tasks plugin incompatibility

### ISSUE THREAD

**Issue by kud3n013** [xhuajin/obsidian-tabs#15]
When I add a block code from [task plugin](https://github.com/obsidian-tasks-group/obsidian-tasks) it doesn't render.
example: 
````tabs
tab: Task 
```tasks
not done
sort by priority
```
````

**Comment by xhuajin** [comment]
The tasks plugin retrieved the results normally, but did not actively render like the dataivew plugin. I raised an issue with the tasks plugin. https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2941

**Comment by xhuajin** [comment]
The fix will be included in the next Tasks release. The time for the update is unknown.

**Comment by xhuajin** [comment]
The fix for this is now released, in [Tasks 7.6.1](https://github.com/obsidian-tasks-group/obsidian-tasks/releases/tag/7.6.1).
