### ISSUE TITLE
How can I render multi-column-markdown on tabs

### ISSUE THREAD

**Issue by PSVLTT** [xhuajin/obsidian-tabs#17]
Hello,
The first, thank you for this great plugin.

I want to render columns from [multi-column-markdown](https://github.com/ckRobinson/multi-column-markdown)
But my codes do not work.
Can you check it?

My Idea:

![image](https://github.com/xhuajin/obsidian-tabs/assets/142076226/3fea0c9c-acb9-47fa-973b-e4126a0445e8)

My code:

`````tabs

tab: Tab 1
--- start-multi-column: 
```column-settings  
number of columns: 3  

shadow: off
```

# Column 1

--- end-column ---

# Column 2

--- end-column ---

# Column 3

--- end-multi-column
tab: Tab 2

tab: Tab 3

`````

The result:

![image](https://github.com/xhuajin/obsidian-tabs/assets/142076226/0ef3ff26-7aa8-4a2d-8a70-9a397d951057)

**Comment by SilenceIA** [comment]
I found a way to do this, but you need to use multiple notes.
For example, **Note A** contains Tab 1, 2 & 3 and embed sub-notes. 
Then have sub-notes for each Tab:
- Tab1 contains Tab 1 - Column A, B & C
- Tab2 contains Tab 2 - Columns A, B & C
- Tab3 contains Tab 3 - Columns A, B &C

Would look like this,
- Note A
`````
````tabs
tab: Tab 1
![[Tab1]]
tab: Tab 2
![[Tab2]]
tab: Tab 3
![[Tab3]]
````
`````

- Tab1 (and so on),
`````
````tabs
tab: Column 1
Tab 1 - Column 1
tab: Column 2
Tab 1 - Column 2
tab: Column 3
Tab 1 - Column 3
````
`````

It would then look like this,
![image](https://github.com/xhuajin/obsidian-tabs/assets/142595543/72f719ec-ee72-4f2b-b1d5-58ffe61ef595)
![image](https://github.com/xhuajin/obsidian-tabs/assets/142595543/93879d78-44ab-4655-ba52-bfb73c072628)

**Comment by PSVLTT** [comment]
I fixed it.
Use this Plugin [obsidian-columns 3](https://github.com/tnichols217/obsidian-columns) by [tnichols217](https://github.com/tnichols217) instead of [multi-column-markdown](https://github.com/ckRobinson/multi-column-markdown)

![image](https://github.com/xhuajin/obsidian-tabs/assets/142076226/786af44b-531f-4aa1-a54b-0c447422270a)

**Comment by xhuajin** [comment]
> A problem left is can not put #task on the tabs

The fix will be included in the next Tasks release. The time for the update is unknown.

**Comment by PSVLTT** [comment]
> > A problem left is can not put #task on the tabs
> 
> The fix will be included in the next Tasks release. The time for the update is unknown.

 Thank you very much, again 😁
