### ISSUE TITLE
Nested Tabs

### ISSUE THREAD

**Issue by sqepticull** [xhuajin/obsidian-tabs#19]
5x`tabs

tab: DARK ROGUE

3x`tabs

tab: ARMOR

tab: WEAPONS

tab: CONSUMABLES

tab: SKILLS

3 backticks
5 backticks

Why doesn't this work?

**Comment by xhuajin** [comment]
Try v1.1.0

**Comment by sqepticull** [comment]
Works like a charm.  Thank you much.
