### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by DutchPete** [xhuajin/obsidian-tabs#2]
It looks interesting, but I am wondering what it would be used for. Why have tabs within a note instead of headers?

In other words, instead of having tabs you can have headers. So, the info in each tab could be put under an eponymous header.

Furthermore, in order to get the tabs you have to add code blocks to the note, which is more work.

So, you have a nice solution, but to what problem?

Note: this is not criticism of your plug-in, on the contrary, I somehow am attracted to it but I cannot immediately see a practical application of it.

**Comment by xhuajin** [comment]
You are right, it is possible to implement the classification function using only the title.

For me, I would like to see some contents with horizontal and comparative significance displayed in the same block. This requirement originated when I recorded the leetcode algorithm problem before. For example, I used python, java and c to solve this problem at the same time. It allows me to see all the code in one area, and I don't like pages that are so long that I have to scroll down so I can't see what's above.

Putting the same level of text in the same area to read is the purpose of writing this plugin. For example, you can try putting multiple DataViews in tabs. I'll look like

![image](https://github.com/xhuajin/obsidian-tabs/assets/114134574/7c93c13b-cdc7-48dc-a671-b09610a0c947)

**Comment by DutchPete** [comment]
Thanks for your explanation.
