### ISSUE TITLE
List of tabs in 2 rows

### ISSUE THREAD

**Issue by Fertion** [xhuajin/obsidian-tabs#20]
If the list is too big to fit, it would be cool if you could make tabs display in 2 rows, 1 above the other.

This is especially handy if you need to place such a note in the sidebar (for example, to display tasks there), and the width there becomes too small.

**Comment by xhuajin** [comment]
I don't quite understand your description. Can you take a screenshot or draw it roughly.

**Comment by Fertion** [comment]
Let's say there are 10 tabs.
How it works now:
![image](https://github.com/user-attachments/assets/8b5b57d4-bcf6-4d39-a5bc-d98bf151b2ce)
I suggest:
![image](https://github.com/user-attachments/assets/c2e2d88f-a7c8-4992-9b78-a5ad4c727146)

**Comment by xhuajin** [comment]
It can easily implement this effect by css, like
.tab-container .tab-nav .tab-nav-item-wrapper {
  flex-wrap: wrap;
}

.tab-container .tab-nav .tab-nav-button {
  margin: 4px 33px 0 0;
}

![image](https://github.com/user-attachments/assets/0603456f-ffd7-4e3a-879d-74a4a28acd13)

**Comment by Fertion** [comment]
That's exactly what it is. Thank you very much.
