### ISSUE TITLE
Line size scales incorrectly

### ISSUE THREAD

**Issue by dimiarbre** [xhuajin/obsidian-tabs#27]
Hello
First of all, thanks for the great work.
With the latest release (1.1.3), something was changed in terms of line size. While previously, lines in a tabs environment did fit my entire text area, now the line breaks are extremely early, yielding to inconsistent text size. See the image below.
![Screenshot from 2024-07-22 12-11-52](https://github.com/user-attachments/assets/50415208-e212-4057-be56-88b0947b472d)

This happens both in live preview or reading view.

In my obsidian settings, I always have the "Editor/readable line length" option turned off, yielding smaller margins. This could be a source of the issue, as the line size seems ok with this option turned on (the default). But I'd rather keep this option, as this margin size is better for me.

I don't believe I had such a problem with previous versions. I could do the test if needed.

Steps to reproduce:
- Open a sandbox vault
- Install tabs
- Turn off  "Editor/readable line length" in settings.
- Add some text and a tab, and look at the line breaks.

**Comment by xhuajin** [comment]
Thank you for liking it! In 1.1.3 I added the max-width attribute to the line width, I ignored users with full width. I will improve this in the next version. Thank you for your detailed feedback!

**Comment by Narakir** [comment]
If people are interested you can brute force fix it with this CSS snippet :

```
.tab.container {
display: contents;
}
```

WARNING, it's going to break a few of the added features but its going to work like it did before this new version.

**Comment by arteny** [comment]
> If people are interested you can brute force fix it with this CSS snippet :
> 
> ```
> .tab.container {
> display: contents;
> }
> ```
> 
> WARNING, it's going to break a few of the added features but its going to work like it did before this new version.

this not works for me, but works if change style name to `.tab-container`

**Comment by sbsamarski** [comment]
> Thank you for liking it! In 1.1.3 I added the max-width attribute to the line width, I ignored users with full width. I will improve this in the next version. Thank you for your detailed feedback!

Can't wait for the new update with the correction. 👍🏻 
This bug messes up my dashboard (now with tabs). It's half width now.

**Comment by darathomascyber** [comment]
I guess I'm not the only one with this problem; I just posted about this, and then I saw this post and everyone's comment under it. I hope that it gets fixed really soon! I'm adding my own pics here too. The first shows what my dashboard normally looks like, and the 2nd pic shows what it looks like since I did the update a couple of days ago...

![Dashboard Why 1](https://github.com/user-attachments/assets/d030e4cb-1dbf-482f-a824-10cbeea4ba40)
![Dashboard Why 2](https://github.com/user-attachments/assets/c9d05894-cc37-4f4b-84ea-9208ff7812bb)

**Comment by darathomascyber** [comment]
> Thank you for liking it! In 1.1.3 I added the max-width attribute to the line width, I ignored users with full width. I will improve this in the next version. Thank you for your detailed feedback!

Thanks for letting us know :-) When can we expect the next plugin update with the correction?

**Comment by xhuajin** [comment]
Version 1.1.4 fixes this bug. Feel free to update and give it a try!

**Comment by dimiarbre** [comment]
I just tested it, and it works perfectly for me!
Thanks a lot for the swift fix!

**Comment by sbsamarski** [comment]
> Version 1.1.4 fixes this bug. Feel free to update and give it a try!

OK, now it's the same as before. Thanks.
However, that "before" was also narrower than normal text outside of a tab frame. If I tap on the inner side a frame around the tab container shows, and you can see it has large inner bezels for any content inside the tab frame. 
Basically, the text inside a tab has narrower width than the text outisde the tab.
This is easy to see if you put a code block inside a tab, it will be some 10% narrower than a code block outside of the tab.

Why is that? Can those inner bezels be reduced or eliminated?

**Comment by xhuajin** [comment]
> Can those inner bezels be reduced or eliminated?

In Tabs setting -> Appearance -> Tab contents -> Tabs contents padding. Enter an css padding that you feel comfortable. If you want narrower width try: 1em.

**Comment by sbsamarski** [comment]
> > Can those inner bezels be reduced or eliminated?
> 
> In Tabs setting -> Appearance -> Tab contents -> Tabs contents padding. Enter an css padding that you feel comfortable. If you want narrower width try: 1em.

Oh yes, thank you. I thought those tabs at the bottom were just empty visuals, an example of how the tabs look like. That text was meaningless, so I never bothered to click on those other tabs.
