### ISSUE TITLE
Disabling Code formatting for Tabs code block.

### ISSUE THREAD

**Issue by DeusEx01** [xhuajin/obsidian-tabs#28]
Hi! Firstly, I want to say thanks for your plugin. It's simple yet effective feature!

And the "Feature request" is adding an ability to turn off code style for tabs. What I mean is when we have some content that we would like to change from time to time, we have to work without any MD formatting for text because we have code formatting (without syntax highlight). 
Here is how it looks without tabs. It has native formattings for things like `#tags` or  `>quotes`  or `# Headers` and so on.
![image](https://github.com/user-attachments/assets/d483dc5b-0176-49a2-8f2d-03c8f6fb011e)

But in ` ```tabs ` we lose all the formattings and have to work with code formatting.
![image](https://github.com/user-attachments/assets/b707b65c-b491-4c1f-b04e-b9ac631222b6)

So I think it would be cool to turn off such ```tabs code format or adding an option to turn it off. 

Right now, I use the plugin only for Dataview queries like personal book Library
![image](https://github.com/user-attachments/assets/92089290-4470-4d8c-8e86-e5889599759c)

**Comment by xhuajin** [comment]
Thank you for your liking! The effect of using tabs in conjunction with dataview looks great. Would you like me to put your example of using dataview in tabs into README's Showcase? I'll put your name up there, too.

I understand the meaning of "turn off code style for tabs". In fact, this rendering uses the API provided by ob to render text into reading mode (MarkdownRenderer.render()). The reason for not using live mode editor directly is that ob does not seem to have exposed its cm5+cm6 editor (or I haven’t found it). I was also troubled by the limitation of only being able to edit the source code. My current solution is to write a cm6 editor that allows for quick editing with a double-click. I will continue to look for better solutions in the future.

(ps. English is not my mother tongue. If there are any irregularities in my expression, please point them out to me. Thank you for your feedback!)

**Comment by DeusEx01** [comment]
@xhuajin Of course you can use the showcase as you wish. By the way, it's made with my snippet for such **Cards view** (https://github.com/DeusEx01/Cards-View-snippet)
Also, I use **Tabs** in mobile too, so it looks like this:
![image](https://github.com/user-attachments/assets/36c5b48d-f8c1-4be6-ab85-fcc4d6908b7e)

And thanks for extended answer about the issue. Unfortunately, I'm not an advanced JS user, so I can't give any hint about solving the issue.

(p.s. English is not my mother tongue either)

**Comment by xhuajin** [comment]
Thank you very much! I will put the example you provided into the README in the next update. I'll try to find a better solution in the future.

**Comment by xhuajin** [comment]
Tabs has been updated to 1.1.4, and the use case you shared has been included in the README. Due to the large number of images in the showcase section, I’ve moved the entire section further down. Thank you again for your contribution!

**Comment by DeusEx01** [comment]
Thanks for the update. How to use images is up to you, of course. 
The only thing I don't understand is why are these images have broken links =) 
![image](https://github.com/user-attachments/assets/c1ea3b6d-4cbc-42aa-a405-1480a7cee713)
I'm not an advanced GitHub user, so I don't know if it's a common behavior.
