### ISSUE TITLE
Maybe a border can be added.

### ISSUE THREAD

**Issue by yifan0414** [xhuajin/obsidian-tabs#29]
I really like this plugin; it's beautiful and elegant. However, as a special component, could an option be provided in **preview mode** to add a border, similar to the code block in edit mode? like this
![image](https://github.com/user-attachments/assets/86608ca9-5304-43b9-9677-42d41c59e783)

**Comment by xhuajin** [comment]
Thank you for liking it!

In fact, this code block has a border by default (the effect is shown in the image when the mouse is hovering), and some themes hide this border (such as minimal). In the next version I will add custom content for border.
