### ISSUE TITLE
[BUG] Tabs will blink after closing setting

### ISSUE THREAD

**Issue by Moyf** [xhuajin/obsidian-tabs#33]
After updated to newest version (1.1.4), after I open and close Setting, all my tabs would blink (from Name into "No file" then back to name)

---

更新完 1.1.4 插件之后，关闭 OB 的设置界面时，标签页会发生闪动。
不确定是不是插件冲突引起的，但之前没有这个问题。

禁用插件后再重启 OB 可以恢复正常。

在沙盒仓库测试了，也会有一样的现象 （不过沙盒文件特别少所以是飞快闪动一下）

另外沙盒仓库安装的时候发现初次安装就会出现 Update 按钮：
![image](https://github.com/user-attachments/assets/4de51fc2-34f2-4535-94d9-5d299e4a1a70)

**Comment by xhuajin** [comment]
标签页闪动是因为我写了一个更改设置之后重新渲染所有已打开的markdown页面，下一版把改为可选吧。出现Update按钮是我版本号写错了，我现在改好了，感谢提醒！

**Comment by Moyf** [comment]
> 标签页闪动是因为我写了一个更改设置之后重新渲染所有已打开的markdown页面，下一版把改为可选吧。出现Update按钮是我版本号写错了，我现在改好了，感谢提醒！

嗯，这样的话建议检测一下 **插件的设置是否有发生改动** ，因为之前的表现是只要我打开再关闭设置，哪怕什么都没修改，它也会默认闪烁 🤔

**Comment by xhuajin** [comment]
确实，我之前没太注意这个刷新的闪烁，下一版再增加个有修改再refresh

**Comment by mindfad** [comment]
感谢您努力解决这个问题！澄清一下，对我来说，“闪存”的另一个问题是，当离开设置时，它会从您当前的活动选项卡中阻止控制，并将活动选项卡更改为另一个活动选项卡。我在两个窗格上有多组选项卡，所以这可能是一个促成因素。

**Comment by xhuajin** [comment]
1.1.6将保存自动刷新页面改为了设置项，可以取消后手动刷新
