### ISSUE TITLE
Nested Tabs within Nested Tabs

### ISSUE THREAD

**Issue by sqeptyk** [xhuajin/obsidian-tabs#39]
After two levels of tab code blocks, a third doesn't work.  I used 5 backticks for the highest level and 3 for the other two levels.  Is there a way to nest tabs within nested tabs?

**Comment by xhuajin** [comment]
You can check that the syntax you use when nesting is correct

![image](https://github.com/user-attachments/assets/e77eeec4-7adc-4c6f-9d60-7515713ca804)

**Comment by xhuajin** [comment]
There is no limit to the number of backquotes, only the outer tabs needs to be more than the inner tabs. If it's blank, you probably forgot to add `tab:`

**Comment by sqeptyk** [comment]
Thanks again.
