### ISSUE TITLE
Conflicts with 2 plugins

### ISSUE THREAD

**Issue by accept82** [xhuajin/obsidian-tabs#41]
Good afternoon
Tabs plugin 1.1.6 conflicts with two plugins:
- Virtual Linker l Glossary
- Supercharged Links
When one of the plugins is enabled, the Tabs plugin stops working

**Comment by xhuajin** [comment]
Thanks for the feedback!

It is the newly added function of rendering title that conflicts with them. I'm considering whether to set rendering title as optional to avoid conflicts.

**Comment by accept82** [comment]
I really hope you solve these problems, your plugin is really useful for me

**Comment by xhuajin** [comment]
The conflict has been resolved. Release 1.1.7 after fixing another issue.

**Comment by xhuajin** [comment]
Try 1.1.7

**Comment by accept82** [comment]
Everything worked great!
Thank you for quickly correcting the error!

**Comment by nanjingman** [comment]
Still conflict with Virtual Linker l Glossary (another good plugin). Please help!
