### ISSUE TITLE
Issues when embedding task reporting in tabs

### ISSUE THREAD

**Issue by 27escape** [xhuajin/obsidian-tabs#5]
This is a really useful plugin and helps to make my dashboard nice and clean, however I have a problem, I cannot embed task reporting, dataview is fine and embedding other documents that have task reporting is fine too, I have attached a sample of the problem

you will need to be using obsidian tasks and have some tasks created for the current year

[Tabs testing.md](https://github.com/user-attachments/files/15817418/Tabs.testing.md)

Cheers
Kevin

**Comment by xhuajin** [comment]
The tasks plugin retrieved the results normally, but did not actively render like the dataivew plugin. I raised an issue with the tasks plugin. https://github.com/obsidian-tasks-group/obsidian-tasks/issues/2941

**Comment by xhuajin** [comment]
The fix will be included in the next Tasks release. The time for the update is unknown.

**Comment by 27escape** [comment]
Fantastic. Thank you

**Comment by xhuajin** [comment]
The fix for this is now released, in [Tasks 7.6.1](https://github.com/obsidian-tasks-group/obsidian-tasks/releases/tag/7.6.1).
