### ISSUE TITLE
Question about headers inside the Tabs

### ISSUE THREAD

**Issue by RoG7eR** [xhuajin/obsidian-tabs#58]
So when using the tabs-plugin: Is there any way to get the prompt for Header inside the tab? It doesnt seem to be recognized like normal headers
When I use "[[##]]" to search for headers for linking, the one inside the tab is not recognized

![image](https://github.com/user-attachments/assets/a75c35f8-ccf4-4349-88cc-8cfd763c393a)

**Comment by xhuajin** [comment]
Anything within the code block will be treated as plain text in obsidian. as well the heading.

**Comment by RoG7eR** [comment]
Oh okay, I see
