### ISSUE TITLE
Breaks Obsidian

### ISSUE THREAD

**Issue by Cat-From-Discord** [xhuajin/obsidian-tabs#6]
When I use the plugin in my vault all the buttons just stop working. When I force close obsidian and reopen it it gets stuck on the loading screen. 

**What I tried:**
- Restart computer
- Reinstall obsidian
- Delete everything unnecessary in .obsidian
- Use another app to remove the " ```tabs``` " (I dont know what its called)
 
The last one makes obsidian work perfectly as usual, leading me to the conclusion that it has something to do with the plugin.

**Comment by xhuajin** [comment]
I’m really sorry to hear that you’re going through this vicious bug. Hoping things improve for you soon.
