### ISSUE TITLE
[Question] 插件在编辑模式无效, 可能是什么原因

### ISSUE THREAD

**Issue by XMB-7** [xhuajin/obsidian-tabs#7]
在个人库里, 编辑模式下显示不出来 (显示效果如下), 但在沙箱库里就是好的.
![image](https://github.com/xhuajin/obsidian-tabs/assets/65625632/36d017cb-7943-4d8b-99e0-32bfb7bc798e)

以为是哪个插件有冲突, 但已经把所有其他插件都关了, 完了ob设置也跟沙箱库一致了, 但就是显示不出来 (显示效果如下), 实在没招了, 来问问看可能是哪里出了问题?
![image](https://github.com/xhuajin/obsidian-tabs/assets/65625632/cb5174a4-fdb4-4f98-85a8-98b23cd61ed0)

**Comment by xhuajin** [comment]
我暂时还没有遇到过这个 bug，Tabs 的逻辑是渲染 ```tabs ``` 代码块，应该是不太有和其他插件冲突的机会。可以提供下更多信息，或者等我也遇到这个bug的时候可能才能定位解决。

**Comment by XMB-7** [comment]
我重装了obsidian, 现在能显示了, 但直接双击进行编辑还是有显示问题, 而且此时必须刷新页面才能恢复(比如先切换到其他页面再切换回). 或许又是插件冲突? 我插件有点多, 排查起来太麻烦了, 得等哪天有空闲的, 毕竟现在起码能用了. 
ps.需要哪些更多信息

![image](https://github.com/xhuajin/obsidian-tabs/assets/65625632/b7f8fa30-e43d-442c-bb64-a8d786eb7400)
